### PR TITLE
fix: too much zoom on multi camera devices for tracking

### PR DESCRIPTION
**Pull request by mateusmb**
This PR solves issue #105, where multi camera devices has the default camera selected, which in case is too zoomed in. This doesn't break the camera usage for devices which doesn't have this issue.

### CODE REVIEW

**Comment by hiukim** [comment]
@mateusmb Thanks for the PR. Can you help me understand what are you trying to fix?

I saw you are trying to select a camera with this label whenever possible: "camera2 0, facing back". What's the reason for doing that?

**Comment by Sov3rain** [comment]
@hiukim It's a bit of a hacky solution, there is no real answer for "why" as I understand. This is just try and error on Samsung and other multiple lenses phones.

See [this issue](https://github.com/AR-js-org/AR.js/issues/303#issuecomment-974831181) for more details, as AR,js seems to have the same problem.

**Comment by JxstWieslaw** [comment]
Hie @hiukim @Sov3rain @mateusmb

**Comment by hiukim** [comment]
Please refer to this update on how to pick camera:
https://github.com/hiukim/mind-ar-js/issues/105#issuecomment-1575478582

Closing this PR. thx all.

**Pull request closed without merging**
